version: "3.8"
services:
  backend:
    container_name: app-backend
    restart: always
    build: 
      context: ..
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
  database:
    container_name: app-db
    image: mongo
    ports:
      - "27017:27017"
  client: 
    container_name: app-frontend 
    build: 
      context: ..
      dockerfile: client/Dockerfile
    ports: 
      - "3000:3000"
    volumes: 
      - ..:/workspace:cached
      # - ./client:/app
      # - /app/node_modules
    depends_on: 
      - database 
      - backend 
    command: /bin/sh -c "while sleep 1000; do :; done"